export const initialUsers = [
  {
    id: 1,
    name: 'Dave Richards',
    email: 'dave@mail.com',
    contact: '+91 8332883854',
    firstName: 'Dave',
    lastName: 'Richards',
    yearOfBirth: '1995',
    gender: 'Male',
    phoneNumber: '8332883854',
    alternatePhone: '',
    address: '123 Main Street',
    pincode: '560001',
    domicileState: 'Karnataka',
    domicileCountry: 'India'
  },
  {
    id: 2,
    name: 'Abhishek Hari',
    email: 'hari@mail.com',
    contact: '+91 9876543210',
    firstName: 'Abhishek',
    lastName: 'Hari',
    yearOfBirth: '1996',
    gender: 'Male',
    phoneNumber: '9876543210',
    alternatePhone: '',
    address: '456 Second Street',
    pincode: '600001',
    domicileState: 'Tamil Nadu',
    domicileCountry: 'India'
  },
  {
    id: 3,
    name: 'Nishta Gupta',
    email: 'nishta@mail.com',
    contact: '+91 8765432109',
    firstName: 'Nishta',
    lastName: 'Gupta',
    yearOfBirth: '1997',
    gender: 'Female',
    phoneNumber: '8765432109',
    alternatePhone: '',
    address: '789 Third Street',
    pincode: '110001',
    domicileState: 'Delhi',
    domicileCountry: 'India'
  }
];
